# Generated by Django 5.0.4 on 2024-05-28 11:01

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to='', verbose_name=myapp.models.user_directory_path),
        ),
    ]
